### ISSUE TITLE
feature: Custom Validators (webhooks)

### ISSUE THREAD

**Issue by stanistan** [cashapp/cmmc#3]
Currently, cmmc only supports doing [JSONSchema][1] validation. 

It would be nice to support something like a custom validators via some syntax in the `MergeTarget` like:

```yaml
   # ....
   data: 
     key:
       validator:
         url: <...>
```

For this to be usable, this should also have a proto definition of a request/response spec of a sort.

[1]: https://json-schema.org/
