### ISSUE TITLE
docs/feature: How to deploy

### ISSUE THREAD

**Issue by cheesimp** [cashapp/cmmc#5]
I wanna use cmmc for managing my eks auth but I did not find any information explaining how to deploy it on a kubernetes cluster.
Is there any guide I can follow?
Thanks

**Comment by stanistan** [comment]
In lieu of docs being available. 

- All of the deployment configuration currently lives in `config/`.
- You can deploy a cmmc in your cluster using `kustomize` 

--- 

```yaml
images: 
  name: controller
  newName: cashapp/cmmc
  newTag: v0.0.1

resources:
- config/crd
- config/rbac
- config/manager
```

**Comment by bappr** [comment]
@stanistan thanks a lot!

It should be
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cmmc-system
namePrefix: cmmc-

images: 
-  name: controller
    newName: cashapp/cmmc
    newTag: v0.0.1

resources:
- path/to/config/crd
- path/to/config/rbac
- path/to/config/manager
```

but then works fine!
